version: '3'

services:
  jira-container:
    depends_on:
      - postgres-container
    image: blacklabelops/jira   #meaning JIRA software and pulled directly from dockerhub
#    build: .      # not building my own custom image yet
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jirauser@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=jiradbpass'
      - 'SETENV_JVM_MINIMUM_MEMORY=1024m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Atlassian Jira Software"
      com.blacklabelops.service: "jira"

  postgres-container:
    image: postgres
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jiradbuser'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jiradbpass'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge


### Copy yaml file
# curl -O https://raw.githubusercontent.com/h-garcia/docker/master/jira/docker-compose.yml
# based on https://github.com/blacklabelops/jira


### Running and setting JIRA

  # go to domaim
  # postgres db= jiradb
  # postgres user= jiradbuser
  # postgres pass= jiradbpass
  
  ## go to advanced.. 
  # change server to service_name (postgres-container)
  # default postgres port = 5432
